repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 24.4.2 # Use the latest stable version
    hooks:
      - id: black
        language_version: python3.11 # Specify your target Python version
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0 # Use the latest stable version
    hooks:
      - id: flake8
  # --- OR Using Ruff (Recommended for performance) ---
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.4.4 # Use the latest stable version
  #   hooks:
  #     - id: ruff # Linter
  #       args: [--fix, --exit-non-zero-on-fix] # Auto-fix issues
  #     - id: ruff-format # Formatter
  # --------------------------------------------------
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0 # Use the latest stable version
    hooks:
      - id: mypy
        # args: [--strict] # Consider adding --strict for more rigorous type checking later
        additional_dependencies: [types-requests] # Add types for libraries like requests
