# Generated by Django 5.2 on 2025-05-02 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ["name"], "verbose_name_plural": "Players"},
        ),
        migrations.AddField(
            model_name="player",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(
                help_text="Player's full name (must be unique)",
                max_length=200,
                unique=True,
            ),
        ),
    ]
