# Generated by Django 5.2 on 2025-05-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor_api", "0002_alter_player_options_player_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="team1_h2h_win_pct",
            field=models.FloatField(
                blank=True,
                help_text="Team 1's historical H2H win % against Team 2 before this match",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team1_prev_score",
            field=models.IntegerField(
                blank=True,
                help_text="Team 1's score in their immediately previous match",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team1_prev_wkts",
            field=models.IntegerField(
                blank=True,
                help_text="Team 1's wickets lost in their immediately previous match",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team1_win_pct",
            field=models.FloatField(
                blank=True,
                help_text="Team 1's historical overall win % before this match",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team2_prev_score",
            field=models.IntegerField(
                blank=True,
                help_text="Team 2's score in their immediately previous match",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team2_prev_wkts",
            field=models.IntegerField(
                blank=True,
                help_text="Team 2's wickets lost in their immediately previous match",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team2_win_pct",
            field=models.FloatField(
                blank=True,
                help_text="Team 2's historical overall win % before this match",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="match_id_source",
            field=models.IntegerField(
                help_text="Unique ID from the source data (e.g., Match_Info.csv match_number)",
                unique=True,
            ),
        ),
    ]
