# Generated by Django 5.2 on 2025-05-03 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "predictor_api",
            "0003_match_team1_h2h_win_pct_match_team1_prev_score_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerMatchPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "runs_scored",
                    models.PositiveIntegerField(
                        default=0, help_text="Runs scored by the batsman."
                    ),
                ),
                (
                    "balls_faced",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of balls faced by the batsman."
                    ),
                ),
                (
                    "fours_hit",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of 4s hit."
                    ),
                ),
                (
                    "sixes_hit",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of 6s hit."
                    ),
                ),
                (
                    "dismissal_kind",
                    models.CharField(
                        blank=True,
                        help_text="e.g., caught, bowled, lbw, run out, not out.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "balls_bowled",
                    models.PositiveIntegerField(
                        default=0, help_text="Total balls bowled by the bowler."
                    ),
                ),
                (
                    "runs_conceded",
                    models.PositiveIntegerField(
                        default=0, help_text="Runs conceded by the bowler."
                    ),
                ),
                (
                    "wickets_taken",
                    models.PositiveIntegerField(
                        default=0, help_text="Wickets taken by the bowler."
                    ),
                ),
                (
                    "dots_bowled",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of dot balls bowled."
                    ),
                ),
                (
                    "fours_conceded",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of 4s conceded by the bowler."
                    ),
                ),
                (
                    "sixes_conceded",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of 6s conceded by the bowler."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.ForeignKey(
                        help_text="Link to the match.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_performances",
                        to="predictor_api.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        help_text="Link to the player.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performances",
                        to="predictor_api.player",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Match Performance",
                "verbose_name_plural": "Player Match Performances",
                "ordering": ["-match__date", "player__name"],
                "unique_together": {("player", "match")},
            },
        ),
    ]
